-- Membuat tabel products
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_barang VARCHAR(255) NOT NULL,
    kategori VARCHAR(100) NOT NULL,
    deskripsi TEXT,
    stok INTEGER NOT NULL CHECK (stok >= 0),
    harga NUMERIC(15, 2) NOT NULL,
    supplier VARCHAR(255) NOT NULL,
    tanggal_masuk DATE DEFAULT CURRENT_DATE,
    
    -- Status otomatis berdasarkan stok
    status VARCHAR(50) GENERATED ALWAYS AS (
        CASE 
            WHEN stok = 0 THEN 'Habis'
            WHEN stok <= 10 THEN 'Menipis'
            ELSE 'Aman'
        END
    ) STORED
);

-- Menambahkan 10 data dummy realistis untuk gudang
INSERT INTO products (nama_barang, kategori, deskripsi, stok, harga, supplier, tanggal_masuk) VALUES
('Kardus Packing Medium', 'Packaging', 'Kardus coklat ukuran 30x20x15 cm untuk pengiriman barang', 500, 3500.00, 'PT Surya Kertas', '2023-11-01'),
('Lakban Bening Daimaru', 'ATK', 'Lakban bening ukuran 2 inch x 90 yard', 150, 12000.00, 'CV Makmur Sejahtera', '2023-11-15'),
('Bubble Wrap 50m', 'Packaging', 'Plastik gelembung penahan benturan 1.25m x 50m', 25, 145000.00, 'PT Plastik Indo', '2023-12-05'),
('Rak Besi Siku Lubang', 'Furniture', 'Rak penyimpanan gudang 5 susun kapasitas 100kg/ambalan', 8, 450000.00, 'Toko Besi Jaya', '2023-10-10'),
('Palet Kayu Jati Landa', 'Peralatan', 'Palet alas barang ukuran 120x100 cm standard industri', 0, 75000.00, 'UD Kayu Lestari', '2023-09-20'),
('Kertas HVS A4 80gsm', 'ATK', 'Kertas HVS putih merek PaperOne 1 rim (500 lembar)', 5, 55000.00, 'PT Sinar Mas', '2023-12-10'),
('Spidol Marker Hitam', 'ATK', 'Spidol permanen Snowman warna hitam', 120, 8500.00, 'CV Makmur Sejahtera', '2023-12-01'),
('CCTV Indoor Xiaomi', 'Elektronik', 'Kamera pengawas pintar resolusi 1080p dengan night vision', 45, 385000.00, 'PT Teknologi Maju', '2023-11-25'),
('Mesin Printer Label Thermal', 'Elektronik', 'Printer cetak resi Xprinter USB Bluetooth', 0, 650000.00, 'PT Teknologi Maju', '2023-10-05'),
('Stiker Label Fragile', 'Packaging', 'Stiker peringatan barang mudah pecah 1 roll isi 500 pcs', 12, 25000.00, 'Percetakan Indah', '2023-11-10');
